language: python
python:
  - '3.6'
  - '3.5'
  - '2.7'
jobs:
  include:
    - python: '3.6'
      env: EXTRA_TESTS=true
    - python: '3.5'
      env: EXTRA_TESTS=true
    - python: '2.7'
      env: EXTRA_TESTS=true

script: env $EXTRA_TESTS  ./tests/unit/testing.py