language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'

install:
  - pip install -r requirements.txt

script: python tests/unit/testTask.py TaskTestCase.testCreateTask || python3 tests/unit/testTask.py TaskTestCase.testCreateTask
